-- ============================================
-- V017__Consolidate_All_Migrations.sql
-- ============================================
-- Esta migración marca la consolidación de todas las migraciones anteriores (V001-V016)
-- El esquema final ya está aplicado por las migraciones anteriores
-- Esta migración es solo un marcador para documentar la consolidación
-- ============================================

-- El esquema completo ya existe desde las migraciones V001-V016
-- No se requieren cambios adicionales en esta migración
-- Las migraciones V001-V016 han sido movidas a la carpeta 'old/' para limpieza